// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG4M7mXj9_5mVk09ZKZHai3prAHpPy9K4',
    appId: '1:641806478624:web:6053c1ee6cdb69090c7b45',
    messagingSenderId: '641806478624',
    projectId: 'amst-flutter-db-2d0ea',
    authDomain: 'amst-flutter-db-2d0ea.firebaseapp.com',
    databaseURL: 'https://amst-flutter-db-2d0ea-default-rtdb.firebaseio.com',
    storageBucket: 'amst-flutter-db-2d0ea.appspot.com',
    measurementId: 'G-P2X5E9BK4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAvhtOz_IEcbp-Y02GdaNeID1gKcQvnw0',
    appId: '1:641806478624:android:7fca3e076f8d04810c7b45',
    messagingSenderId: '641806478624',
    projectId: 'amst-flutter-db-2d0ea',
    databaseURL: 'https://amst-flutter-db-2d0ea-default-rtdb.firebaseio.com',
    storageBucket: 'amst-flutter-db-2d0ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWNZzk6r6OE5UevZlUSp7HvJioBzzeUE0',
    appId: '1:641806478624:ios:13af168da22b75200c7b45',
    messagingSenderId: '641806478624',
    projectId: 'amst-flutter-db-2d0ea',
    databaseURL: 'https://amst-flutter-db-2d0ea-default-rtdb.firebaseio.com',
    storageBucket: 'amst-flutter-db-2d0ea.appspot.com',
    iosClientId: '641806478624-k3gdr8mhhn8jtn8ghtqo6gj201nj747a.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFlutterDb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWNZzk6r6OE5UevZlUSp7HvJioBzzeUE0',
    appId: '1:641806478624:ios:ea6b1c662229a7ea0c7b45',
    messagingSenderId: '641806478624',
    projectId: 'amst-flutter-db-2d0ea',
    databaseURL: 'https://amst-flutter-db-2d0ea-default-rtdb.firebaseio.com',
    storageBucket: 'amst-flutter-db-2d0ea.appspot.com',
    iosClientId: '641806478624-3dj48uct22uklb1mval3em9eebcji39m.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFlutterDb.RunnerTests',
  );
}
